[Feat] Header 컴포넌트 추가 및 auth > login, signup 페이지 기본만 추가
fe9-4/taskify pull request #6
Opened 2024-10-19 08:06 UTC by cccwon2

2024-10-21 02:25 UTC, byeolee1221 requested changes
고생하셨습니다.

2024-10-21 02:25 UTC, byeolee1221 commented on src/app/auth/login/page.tsx
> +"use client";
app router에서 경로를 auth 아래에 login과 signup으로 하시면 사용자도 auth/login, auth/signup으로 접속하게 됩니다. 이 경우에 (auth)로 소괄호 문법 사용하셔서 폴더를 그룹화해주시면 좋을 것 같아요!
(참고: https://nextjs.org/docs/app/building-your-application/routing/route-groups)

2024-10-21 02:25 UTC, byeolee1221 commented on src/app/auth/login/page.tsx
> +          <input
zod schema, react-hook-form 적용하시면 useState와 input의 required 속성, value 속성 등 상당수의 코드를 사용하지 않고도 간편하게 작성하실 수 있습니다.

2024-10-21 02:25 UTC, byeolee1221 commented on src/app/auth/login/page.tsx
> +        <div className="mb-4">
mb-4처럼 반복되는 하위 요소와의 간격같은 경우 해당 하위 요소들의 부모 요소에 flex flex-col space-y-1로 하여 하위 요소들의 마진을 편하게 관리하실 수 있어요!

2024-10-21 02:25 UTC, byeolee1221 commented on src/app/auth/login/page.tsx
> +    <div className="container mx-auto mt-8">
회원가입, 로그인에 공통 적용되는 스타일은 그룹화된 (auth) 폴더의 layout.tsx 파일 만드셔서 공통 스타일 적용하시면 편하게 관리하실 수 있습니다.

2024-10-21 02:25 UTC, byeolee1221 commented on src/components/Header.tsx
> +            <Link className="text-base font-normal md:text-lg" href="/auth/login">
(auth) 폴더로 그룹화하면 /login, /signup으로 지정할 수 있습니다.

2024-10-21 02:25 UTC, byeolee1221 commented on src/app/auth/signup/page.tsx
> +        <div className="mb-4">
비밀번호 확인이 누락된 것 같아요!

2024-10-21 02:25 UTC, byeolee1221 commented on src/app/auth/signup/page.tsx
> +        </div>
이용약관 동의 체크부분도 누락된 것 같습니다!

2024-10-21 02:25 UTC, byeolee1221 commented on src/app/auth/login/page.tsx
> +    </div>
로그인페이지에서는 회원가입페이지로 가는 링크, 회원가입페이지에서는 로그인페이지로 가는 링크가 누락된 것 같아요!

2024-10-21 07:36 UTC, hongggyelim commented
올려주신 PR 타켓 브랜치가 현재 main으로 되어있어서 develop으로 수정 필요할 듯 합니다

2024-10-21 07:57 UTC, cccwon2 commented on src/app/auth/login/page.tsx
> +  const handleSubmit = (e: React.FormEvent) => {
적용했습니다.

2024-10-21 07:57 UTC, cccwon2 commented on src/app/auth/login/page.tsx
> +    <div className="container mx-auto mt-8">
적용했습니다.

2024-10-21 07:57 UTC, cccwon2 commented on src/app/auth/login/page.tsx
> +          <input
적용했습니다.

2024-10-21 07:57 UTC, cccwon2 commented on src/app/auth/login/page.tsx
> +    </div>
적용했습니다.

2024-10-21 07:57 UTC, cccwon2 commented on src/app/auth/signup/page.tsx
> +        <div className="mb-4">
적용했습니다.

2024-10-21 07:57 UTC, cccwon2 commented on src/app/auth/signup/page.tsx
> +        </div>
적용했습니다.

2024-10-21 07:57 UTC, cccwon2 commented on src/components/Header.tsx
> +            <Link className="text-base font-normal md:text-lg" href="/auth/login">
적용했습니다.

2024-10-21 07:58 UTC, cccwon2 commented on src/app/auth/login/page.tsx
> +"use client";
적용했습니다.

2024-10-21 07:59 UTC, cccwon2 commented on src/app/auth/login/page.tsx
> +        <div className="mb-4">
공통되는 부분을 (auth)/layout.tsx 로 빼고 전체적으로 CSS 수정 했습니다.

2024-10-21 08:40 UTC, cccwon2 commented
PR 타켓 브랜치를 develop 로 수정 했습니다.

2024-10-21 14:26 UTC, byeolee1221 approved these changes
수정하신 걸 이제야 확인했네요. 고생하셨습니다!

2024-10-21 14:26 UTC, byeolee1221 commented on src/app/(auth)/login/page.tsx
> +      const setCookieResponse = await fetch("/api/auth/cookie/setCookie", {
axios 적용하면 코드가 좀 더 간결해질 수 있을 것 같아요!

2024-10-21 14:26 UTC, byeolee1221 commented on src/app/(auth)/login/page.tsx
> +            placeholder="••••••••"
비밀번호 placeholder는 '비밀번호를 입력해 주세요'로 나와야할 것 같아요!

2024-10-21 14:26 UTC, byeolee1221 commented on src/app/(auth)/login/page.tsx
> +    formState: { errors, isValid },
formState의 isSubmitting을 사용하시면 제출이 진행중일 때를 catch 할 수 있습니다. 이를 이용해서 아래 disabled 활성화 여부에 활용하실 수 있어요. 이걸 사용하신다면 isLoading 상태도 필요 없어집니다.
그리고 useForm의 reset을 활용해서 폼 초기화에 쓰실 수도 있습니다.

2024-10-21 14:26 UTC, byeolee1221 commented on src/app/(auth)/login/page.tsx
> +    mode: "onChange",
```
defaultValues: {
  email: "",
  password: ""
}
```
위 코드 활용하셔서 기본값 지정할 수 있습니다. 그럼 이 기본값으로 form 제출됐을 때 reset을 활용해서 폼을 초기화하는 데 쓸 수도 있습니다.

2024-10-21 14:26 UTC, byeolee1221 commented on src/app/(auth)/login/page.tsx
> +      toast.error(error instanceof Error ? error.message : "로그인 중 오류가 발생했습니다.");
axios 쓰시면 api에서 지정한 오류메세지도 받아서 toast.error로 띄울 수 있습니다!

2024-10-21 14:26 UTC, byeolee1221 commented on src/zodSchema/authSchema.ts
> +export const UserSchema = z.object({
만드신 스키마 모두 나중에 regex 속성을 써서 정규식을 포함시켜서 개선해봐도 좋을 것 같습니다.

2024-10-21 22:57 UTC, cccwon2 commented on src/zodSchema/authSchema.ts
> +export const UserSchema = z.object({
정규식을 적용해 봤는데 비밀번호 유효성 검사가 좀 엄격해진 느낌이네요.

2024-10-21 22:58 UTC, cccwon2 commented on src/app/(auth)/login/page.tsx
> +      toast.error(error instanceof Error ? error.message : "로그인 중 오류가 발생했습니다.");
axios 를 써서 좀 더 깔끔하게 코드를 리팩토링 했어요~

2024-10-21 23:04 UTC, cccwon2 commented on src/app/(auth)/login/page.tsx
> +    mode: "onChange",
로그인/회원가입 페이지 모두 적용 했어요~

2024-10-21 23:05 UTC, cccwon2 commented on src/app/(auth)/login/page.tsx
> +    formState: { errors, isValid },
로그인/회원가입 페이지에 isSubmitting 을 적용해고 isLoading 은 필요가 없어져서 제거 했어요~

2024-10-21 23:05 UTC, cccwon2 commented on src/app/(auth)/login/page.tsx
> +            placeholder="••••••••"
로그인/회원가입 페이지에 모두 적용했어요~

2024-10-21 23:06 UTC, cccwon2 commented on src/app/(auth)/login/page.tsx
> +      const setCookieResponse = await fetch("/api/auth/cookie/setCookie", {
axios 를 사용해서 코드를 좀 더 간결하게 표시하고 에러 처리도 추가했어요~

2024-10-22 01:58 UTC, hongggyelim commented on src/app/(auth)/login/page.tsx
> +          <Link href={"/signup"} className="text-violet01 hover:underline">
크게 상관없을것같긴 하지만 피그마에는 hover 하지않은 상태에서도 밑줄 스타일 있는거같습니다!

2024-10-22 02:04 UTC, hongggyelim commented on src/app/(auth)/signup/page.tsx
> +        </button>
버튼에 호버 색상 변경 & 제출 진행중일때 회원가입중.. 으로 뜨는것도 추가해야하나요? 
제가 만들어둔 버튼 컴포넌트엔 없어서 필요하면 추가해야할듯합니다

2024-10-22 02:10 UTC, hongggyelim commented on src/app/(auth)/layout.tsx
> +      <button type="button" onClick={() => (window.location.href = "/")} className="mb-6">
- 로고 아래 마진은 mb-6보다 작게 들어가야할 것 같습니다
- 페이지 상단 마진이 피그마에서보다 작게 들어가있네요. 근데 너무 내려갈 필요는 없을것같긴 합니다 ㅎㅎ;

2024-10-22 02:17 UTC, hongggyelim commented on src/components/Header.tsx
> +
이 부분 어떤 로직인지 팀미팅때 설명해주시면 좋겠습니다 !

2024-10-22 02:18 UTC, hongggyelim commented on src/components/Header.tsx
> +    const handleResize = () => {
throttle 이나 debounce 적용하면 어떨까요?

2024-10-22 02:19 UTC, hongggyelim approved these changes
수고하셨습니다

2024-10-22 02:26 UTC, cccwon2 commented on src/app/(auth)/signup/page.tsx
> +        </button>
음... 크게 필요하지는 않을 꺼 같습니다만, loading spinner 로 대체하는게 어떨까요?

2024-10-22 02:27 UTC, hongggyelim commented on src/app/(auth)/signup/page.tsx
> +        </button>
그럼 이부분은 나중에 추가하는걸로 하시죠 ㅎㅎ

2024-10-22 03:15 UTC, ChungO5 commented on src/zodSchema/authSchema.ts
> +    ),
이부분 중복되는 부분이 너무 많은데 변수로 만들어서 재사용 할 수는 없나요?

2024-10-22 03:25 UTC, hyemeeny approved these changes

2024-10-22 03:25 UTC, hyemeeny commented on src/hooks/useAuth.ts
> +        const response = await fetch("/api/user/profile", {
axios로 변경하는게 좋겠습니다! 다 같이 사용할 aixos instance 만들면 좋을 것 같아요 :)

2024-10-22 04:17 UTC, merged

2024-10-22 06:11 UTC, cccwon2 commented on src/app/(auth)/login/page.tsx
> +          <Link href={"/signup"} className="text-violet01 hover:underline">
다음 PR 에 반영하겠습니다.

2024-10-22 06:19 UTC, cccwon2 commented on src/app/(auth)/layout.tsx
> +      <button type="button" onClick={() => (window.location.href = "/")} className="mb-6">
다음 PR에 반영 하겠습니다!

2024-10-22 06:23 UTC, cccwon2 commented on src/components/Header.tsx
> +
팀미팅 때 설명을 못했는데 해당 기능 관련 주석을 달았습니다. 다음 PR 때 확인 가능할 꺼 같아요.

2024-10-22 06:29 UTC, cccwon2 commented on src/components/Header.tsx
> +    const handleResize = () => {
네 다음 PR에 적용하겠습니다.

2024-10-22 06:43 UTC, cccwon2 commented on src/hooks/useAuth.ts
> +        const response = await fetch("/api/user/profile", {
네 다음 PR에 반영하겠습니다.

2024-10-22 06:55 UTC, cccwon2 commented on src/zodSchema/authSchema.ts
> +    ),
commonSchema 에 재사용 가능한 부분들은 따로 뺐습니다. 다음 PR 때 확인해 주세요~